---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-demo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifestes
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
patches:
  - target:
      kind: Deployment
      name: loadgenerator
      namespace: default
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: registry.eqlan.ru:443/boutique-app/loadgenerator:20250919-1736-c9b76c0f