---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: demo-app-manifestes
  namespace: flux-system
spec:
  interval: 1m
  path: "./manifestes"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default