apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- app-demo.yaml
patches:
  - target:
      kind: ServiceAccount
      name: source-controller
      namespace: flux-system
      version: v1
    patch: |-
      - op: add
        path: /metadata/annotations/mytest
        value: "registry.eqlan.ru:443/boutique-app/loadgenerator:20250919-1736-c9b76c0f"