---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: my-test-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/filatof/timeserver
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-test-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./release
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-test-app
