apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: loadgenerator
          image: registry.eqlan.ru:443/boutique-app/loadgenerator:20250919-1736-c9b76c0f