apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - ../base
- ingress-app.yaml

# patches:
# - target:
#     kind: HelmRelease
#     name: nginx
#     namespace: nginx
#   patch: |-
#     - op: add
#       path: /spec/values
#       value:
#         controller:
#           service:
#             type: LoadBalancer
#             annotations:
#               yandex.cloud/load-balancer-type: external
#             externalTrafficPolicy: Local
#           config:
#             use-forwarded-headers: "true"
#             compute-full-forwarded-for: "true"
#             use-proxy-protocol: "false"
#             proxy-body-size: "50m"
#           resources:
#             limits:
#               cpu: 200m
#               memory: 256Mi
#             requests:
#               cpu: 100m
#               memory: 128Mi
#           replicaCount: 1
#           metrics:
#             enabled: true
#         defaultBackend:
#           enabled: true
#           image:
#             repository: defaultbackend-amd64
#             tag: "1.5"