---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-demo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./apps/yandex
  prune: true
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-system
  
