apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adservice.yaml
  - cartservice.yaml
  - checkoutservice.yaml
  - currencyservice.yaml
  - emailservice.yaml
  - frontend.yaml
  - loadgenerator.yaml
  - paymentservice.yaml
  - productcatalogservice.yaml
  - recommendationservice.yaml
  - redis.yaml
  - shippingservice.yaml
patches:
- target:
    kind: Deployment
    name: loadgenerator
    namespace: default
    group: apps
    version: v1
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: "registry.eqlan.ru:443/boutique-app/loadgenerator:20250919-1736-c9b76c0f"