apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- app-demo.yaml
patches:
- target:
    kind: Deployment
    name: loadgenerator
    namespace: default
  patch: |-
    spec:
      template:
        spec:
          containers:
          - name: main
            image: "registry.eqlan.ru:443/boutique-app/loadgenerator:20250919-1736-c9b76c0f"