apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# замена образов для amd64 архетекетуры
images:
  - name: emailservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    newTag: v0.10.3
  - name: checkoutservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    newTag: v0.10.3
  - name: recommendationservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    newTag: v0.10.3
  - name: frontend
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/frontend
    newTag: v0.10.3
  - name: paymentservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newTag: v0.10.3
  - name: productcatalogservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    newTag: v0.10.3
  - name: cartservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    newTag: v0.10.3
  - name: loadgenerator
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    newTag: v0.10.3
  - name: currencyservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    newTag: v0.10.3
  - name: shippingservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    newTag: v0.10.3
  - name: adservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    newTag: v0.10.3

# Патч ресурсов loadgenerator
patches:
  - target:
      kind: Deployment
      name: loadgenerator
      group: apps
      version: v1
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi